cmput404/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from website.forms import LoginForm


urlpatterns = [
	url(r'^service/', include('service.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^', include('website.urls', namespace="website")),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),

]

service/urls.py
from django.conf.urls import url

from . import views

app_name = 'service'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^posts/(?P<id>[^/]+)/comments/?$', views.posts_comments_handler, name='comment_handler'),
    url(r'^posts/?$', views.posts_handler_generic, name='post_handler_generic'),
    url(r'^posts/(?P<id>[^/]+)/?$', views.posts_handler_specific,name='post_handler_specific'),
    url(r'^author/posts/?$', views.author_posts_handler_linked),
    url(r'^author/(?P<id>[^/]+)/posts/?$', views.specific_author_posts_handler),
    url(r'^author/(?P<id>[^/]+)/?$', views.author_handler, name='author_handler'),
    url(r'^friends/(?P<author1_id>[0-9a-z-]+)/(?P<author2_id>[0-9a-z-]+)/?$', views.friend_query_handler, name='friend_query_handler'),
    url(r'^friends/(?P<id>[^/]+)/?$', views.friend_handler_specific, name='friend_handler_specific'),
    url(r'^friends/?$', views.friend_handler, name='friend_handler'),
    url(r'^friendrequest/?$', views.friendrequest_handler, name='friendrequest_handler'),
    url(r'^me/?$', views.get_me, name='me'), #endpoint for angular
]

website/urls.py
#!python
# log/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
#from .views import register

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^register/$', views.UserRegisterForm.as_view(), name='register'),
    url(r'^login/register/$', views.UserRegisterForm.as_view(), name='register'),
    url(r'^make_post/$', views.make_post, name ='make_post'),
    url(r'^profile/$', views.update_profile, name='update_profile'),
    url(r'^requests/$', views.friend_requests, name='requests'),
    url(r'^friends/$', views.friends, name='friends'),
    url(r'^author/(?P<id>[^/]+)/?$', views.view_profile, name='view_profile'),
]

templates/author.html
 {% extends 'base.html' %} {% load staticfiles %} {% block content %}
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="/static/js/js.cookie.js"></script>
<link rel="stylesheet" href="/static/css/author.css" />
<div class="entry" ng-controller='authorCtrl'>

    <!--hardcoded image for now-->
    <div class="jumbotron" id="jumbobody">
        <h2 id="display_name">{{author.displayName}}&nbsp;</h2>
        <img src="/static/images/No_image_available.svg" alt="img" id="profile_picture">
        <span id="author_id" style="display:none" >{{author.id}}</span>
        <span class="info"> First Name: </span> <span class="info_value">{{ author.firstName }}&nbsp;</span>
        <span class="info"> Last Name: </span> <span class="info_value">{{ author.lastName }}&nbsp;</span>
        <span class="info"> Email: </span> <span class="info_value">{{ author.email }}&nbsp;</span>
        <span class="info"> Host: </span> <span id="author_host" class="info_value">{{ author.host }}&nbsp;</span>
        <span class="info"> URL: </span> <span id="author_url" class="info_value">{{ author.url }}&nbsp;</span>
        <span class="info"> Github: </span> <span class="info_value">{{ author.github }}&nbsp;</span>
        <span class="info"> Bio: </span> <span class="info_value">{{ author.bio }}&nbsp;</span>
        {% if request_user.author.id !=  author.id %}
        <button class="btn btn-primary" ng-click="addFriend()" style="margin: 15px 0% 1% 10%;border-radius: 0;" ng-if="isntInFriends()">Add Friend</button>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/base.html
 {% load staticfiles %}

<!DOCTYPE html>
<html ng-app='cmput404client'>

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Auth Demo</title>

	<!-- Core CSS - Include with every page -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/stream.css' %}" rel="stylesheet">
</head>

<body>

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"><span class="sr-only">Toggle navigation</span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	      		</button>
				<a class="navbar-brand" href="/">Home</a>
				<div id="mainmenu" class="navbar-header">
                                        <a class="navbar-brand" style="padding-left:25px" href="/requests">Friend Requests</a>
					<a class="navbar-brand" style="padding-left:25px" href="/friends">Friends</a>
					<a class="navbar-brand" style="padding-left:25px" href="/make_post">Make a Post</a>
				</div>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">

					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="/profile">Profile</a></li>
							<li class="divider"></li>
							<li><a href="/logout">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	{% block content %} {% endblock %}

	<!-- Core Scripts - Include with every page -->
	<!-- we should switch to cdns here instead of serving it ourself, allows users to have a cached version of the scripts -->

	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-sanitize/1.5.9/angular-sanitize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.5.0/showdown.min.js"></script>
	<script src="{% static 'djng/js/django-angular.js' %}"></script>
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/author/author.service.js' %}"></script>
    <script src="{% static 'js/author/author.controller.js' %}"></script>
	<script src="{% static 'js/stream/stream.service.js' %}"></script>
	<script src="{% static 'js/stream/stream.controller.js' %}"></script>
    <script src="{% static 'js/requests/requests.controller.js' %}"></script>
    <script src="{% static 'js/friends/friends.controller.js' %}"></script>
	<script src="{% static 'js/filters/closeDateFilter.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block javascript %} {% endblock %}

</body>

</html>

templates/friends.html
 {% extends 'base.html' %} {% block content %}

<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="/static/js/js.cookie.js"></script>
<link rel="stylesheet" href="/static/css/friends.css" />

<div class="jumbotron" id="jumbobody" ng-controller="friendsCtrl">
    <h1 id="header">Friend List</h1>
    <div ng-repeat="friend in friends" class="friend-container">
        <div class='left-friend-div'>
            <div class="displayname-text">
                <a class="clickable" ng-href="/author/{$friend.id$}">{$ friend.displayName $}</a>
            </div>
            <div class="faded-text">
                {$ friend.host $}
            </div>
        </div>
        <div class='right-friend-div'>
            <a class="glyphicon glyphicon-remove" ng-click="removeFriend(friend.id)"></a>
        </div>
    </div>

</div>
{% endblock %}

templates/home.html

{% extends 'base.html' %}

{% block content %}

<div class="container">
<div class="row">

<div class="jumbotron">
    <h1>Hello</h1>
    <p>You are on your Dashboard</p>
</div>
</div>
</div>
<p style="text-align:center; font-size:larger" >Recent Posts</p>

<div class="entry">
    <div ng-controller='streamCtrl'>
        <div ng-repeat="post in posts | orderBy: '-published'" class="container post-container no-padding">
            <div class="post">
                <div class="post-header">
                    <h1 class="post-title no-margin-top-header">{$ post.title $}</h1>
                    <h1 class="post-date no-margin-top-header" ng-if="post.author.id != getCurrentUser().author.id"> {$ post.published | date: 'MMM d' $}</h1>
                    <h1 class="post-date remove-post-icon" ng-if="post.author.id == getCurrentUser().author.id">
                        <a class="clickable glyphicon glyphicon-ban-circle" ng-click="deletePost(post.id)" title="Delete this post."></a>
                    </h1>
                </div>
                <h3>{$ post.description $}</h3>
                <p class="post-content" ng-bind-html="post.html">{$ post.content $}</p>
                <p class="post-footer faded-text">Posted by <a ng-href="./author/{$post.author.id$}?host={$post.author.host_encoded$}">{$ post.author.displayName $}</a> {$ post.published | closeDateFilter $} @ {$ post.author.host $}</p>
            </div>
            <div class="comment-section">
                <h1 class="no-margin-top-header">Comments</h1>
                <div class="form-group" ng-if="!post.comments.length">
                    <p class="faded-text">There are no comments yet.</p>
                </div>
                <div class="form-group" ng-if="post.comments.length > 0">
                    <div class="comment-container" ng-repeat="comment in post.comments | orderBy: '+published'">
                        <a ng-href='./author/{$comment.author.id$}' class="btn btn-primary profile-picture-button">{$ (comment.author.displayName ? comment.author.displayName[0].toUpperCase() : "?") $}</a>
                        <div class="comment-text">
                            <div><p>{$ comment.comment $}</p></div>
                            <div><p class="faded-text">Posted by <a ng-href="./author/{$comment.author.id$}?host={$comment.author.host_encoded$}"> {$ comment.author.displayName $}</a> {$ comment.published | closeDateFilter $}</p></div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <textarea class="form-control comment" ng-model="post.comment" placeholder="Add a comment" ></textarea>
                </div>
                <div class="form-group col-sm-2">
                    <button class="btn square-button btn-primary form-control" type='submit' ng-click="addComment(post, post.comment)">Comment</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/js.cookie.js"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
    {% if form.errors %}
<p style="text-align:center">Your username and password didn't match. Please try again.</p>
<p style="text-align:center">If you just created your account, an Admin may not have activated it yet. Please try again later.</p>

{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% endif %}
{% endif %}
 <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<p class="bs-component">
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
</p>
<p class="bs-component">
<center><input class="btn btn-success btn-sm" type="submit" value="login" /></center>
</p>
<input type="hidden" name="next" value="{{ next }}" />
</form>
<p style="text-align: center">Don't have an Account? Register <a href="register">here!</a></p>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
$("div#mainmenu").css("display","none");
{% endif %}
</script>

{% endblock %}

templates/make_post.html
{% extends 'base.html' %}

{% block content %}
 <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
 <script src="/static/js/js.cookie.js"></script>
<div class="container">
<div class="row">

<div class="jumbotron">
    <p>Make a post!</p>
{% if error_message %}
   <p><strong>{{error_message}}</strong></p>
{% endif %}
  <div>
  <!--TODO need to where figure out where to send this -->
  <form action="./" method="POST" id="makepost">
  {% csrf_token %}
  <div class="form-group">
    <label for="title">Title</label>
    <input type ="text" id="title" name="title" placeholder="Title" class="form-control">
  </div>
   <div class="form-group">
    <label for="description">Description</label>
    <input type="text" id="description" name="description" class="form-control" placeholder="Description">
   </div>
   <div class="form-group">
    <label for="content">Content</label>
    <textarea rows="4" cols="50" id="content" name="content" form="makepost" class="form-control" placeholder="Content"></textarea>
   </div>
    <div class="form-group">
      <label for="cat">Categories</label>
      <input type ="text" id ="cat" name="categories" class="form-control" placeholder="Categories (separate by comma)">

    </div>
   <div class="form-group">
    <label for="visible">Visibility</label>
   <select id="visible" name="visibility" class="form-control">
           <option value="PRIVATE">Me Only</option>
           <option value="FRIENDS">Your friends on all server </option>
           <option value="FOAF">Friends of friends </option>
           <option value="SERVERONLY">Server Only </option>
           <option value="PUBLIC">All</option>
   </select>
   </div>
   <div class="form-group">
    <label for="texttype">Text Type</label>
    <select id="texttype" name="contentType" class="form-control">
           <option value="text/plain">Text</option>
           <option value="text/x-markdown">Markdown</option>
   </select>
   </div>
   <input type="submit" value="Post" id="submitpost" class="btn btn-default">
   </form>
   </div>


    <script type='text/javascript'>



$("#makepost").submit(function(e){

    e.preventDefault();

    var data = {
        'source': window.location.href,
        'origin': window.location.href
    }

    var Form = this;
    var csrftoken = Cookies.get('csrftoken');

    //Gathering the Data
    //and removing undefined keys(buttons)
    $.each(this.elements, function(i, v){
            var input = $(v);
        data[input.attr("name")] = input.val();
        delete data["undefined"];
    });

    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
    });

    //Form Validation goes here....

    //Save Form Data........
    $.ajax({
        cache: false,
        url : '{% url 'service:post_handler_generic'%}',
        type: "POST",
        dataType : "json",
        data : data,
        context : Form,
        success : function(callback){
            //Where $(this) => context == FORM

            //$(this).html("Received HTTP 200. Post should now be in database.");
            window.location.href = "{% url 'website:home'%}"

        },
        error : function(xhr, thrownError){
            console.log(xhr.status);
            console.log(thrownError)
            $(this).html("Error!");
        }
    });
  });
    </script>
</div>
</div>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
<div class="row">

<div class="jumbotron">

<h2>{{ user.username }}'s Profile</h2>
    
<form method="post" action="/profile/">
  {% csrf_token %}
  {{ profile_form.as_p }}
  <button type="submit" class="btn btn-default">Save changes</button>
</form>
{% endblock %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div></div></div>

templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">

<div class="jumbotron">
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form %}
  <div id="{{ field.auto_id }}_container">
    {{ field.help_text }}
    <div class="form-group">
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.auto_id }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Register" class="btn btn-default"/>
</form>
{% endblock %}


{% block javascript %}
<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
$("div#mainmenu").css("display","none");
{% endif %}
</script>
</div>
</div>
</div>
{% endblock %}

templates/register_success.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="row">
<div class="entry">
<div class = "jumbotron" id="jumbobody">
<p>You have successfully registered!</p>
<p>When an Admin verifies your account, you will be able to use the site!</p>

<p> Return to the <a href="/">Login</a> Page</p>
</div>
</div>
</div>
</div>
{% endblock %}



{% block javascript %}

<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
$("div#mainmenu").css("display","none");
{% endif %}
</script>

{% endblock %}

templates/requests.html
{% extends 'base.html' %}

{% block content %}

<link rel="stylesheet" href="/static/css/friendrequest.css"/>
<div class = "jumbotron" id="jumbobody" ng-controller='requestCtrl'>
    <h1 style='margin-bottom: 0.5em;'>Friend Requests</h1>
    <div ng-repeat='request in friend_requests' class='request'>
        <div class="request-text">
            You've received a friend request from <a ng-href='{$ "/author/" + request.author.id $}'>{$ request.author.displayName $}</a>
            <div class="faded-text">
                {$ request.created | closeDateFilter$}
            </div>
        </div>
        <div style="" class="accept-button">
            <button class="btn btn-xs btn-primary" ng-click='acceptRequest(request)'>Accept</button>
        </div>

    </div>
</div>

{% endblock %}